### ISSUE TITLE
SoftStep 2 compatibility?

### ISSUE THREAD

**Issue by aspiers** [amiguet/foococo#1]
Thanks for this awesome project!

According to http://linuxmusicians.com/viewtopic.php?f=6&t=13230 this software only works with the original SoftStep, not SoftStep 2.  Is that true, and if so, any idea how hard it would be to get it working with the new one?  I am considering buying one, and I am a Python developer with a reasonable amount of MIDI experience, but I have no clue when it comes to firmware or low-level USB/MIDI drivers.

**Comment by amiguet** [comment]
The current code works only with the SoftStep 1, but I had a few hours to try a SoftStep 2 and I'm quite sure it would be very easy to adapt the software for this device. I've got a sketch of code, but did not publish it because I cannot test it. If you're interested in testing it, I'll gladly make a branch with the modified code.
BTW, FooCoCo is all about python and MIDI - except for a few sniffed SysEx messages to get the SoftStep in the right mode, it's basically a realtime MIDI stream processing software.

**Comment by aspiers** [comment]
Thanks a lot - yes please publish that branch!  I may have access to a SoftStep 2 next week.

**Comment by amiguet** [comment]
I pushed a new branch named softstep2. Please test it with a SoftStep2 and tell me if it works. If it does, I'll merge the changes so that the same code can be used for both versions of the device.

**Comment by aspiers** [comment]
Thank you so much! If I have access, I will certainly do this!

**Comment by amiguet** [comment]
Hi Adam, did you have access to a SoftStep 2 yet? please keep me informed!

**Comment by aspiers** [comment]
It turned out to be a SoftStep 1 unfortunately :(

**Comment by amiguet** [comment]
Too bad... so I'll leave this issue open until someone with a SoftStep 2 wants to try.

**Comment by aspiers** [comment]
Good idea.  I found the SoftStep 1 pedals very unreliable and lacking in tactile feedback.  I wonder if the newer model fixes these issues.

**Comment by amiguet** [comment]
I guess that by design, the SoftStep is bound to provide little tactile feedback. However, when I tried a SoftStep 2, it seemed much more sensitive than the 1. So I it might be easier to "feel" how much pressure you apply with a model 2. My SoftStep 1 never felt unreliable, though.

**Comment by aspiers** [comment]
Good to know, thanks!

**Comment by amiguet** [comment]
Just added SoftStep 2 compatibility in branch master (and deleted the softstep2 branch as it is not needed any more).
